services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ats
      POSTGRES_USER: ats_user
      POSTGRES_PASSWORD: ats_pass
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    environment:
      TZ: UTC
    ports:
      - "6380:6379"
